apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ai-devops
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30100   # accessible at minikube-ip:30100
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ai-devops
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30300   # accessible at minikube-ip:30300
  type: NodePort
